# Generated by Django 5.0.3 on 2024-03-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField()),
                ('habitat', models.TextField()),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
            ],
        ),
    ]
